# Generated by Django 5.0.3 on 2024-03-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(max_length=30)),
                ('number_of_tehsils', models.IntegerField()),
                ('number_of_villages', models.IntegerField()),
                ('district_collector', models.CharField(max_length=30)),
                ('famous_spot', models.CharField(max_length=30)),
            ],
        ),
    ]
